<?php

use Illuminate\Database\Seeder;

class SuppliesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('supplies')->insert([
            [
                'id' => '1',
                'name' => '名札',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '210',
                //'division' => '',
            ],
            [
                'id' => '2',
                'name' => '出席ブック',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '0',
                //'division' => '',
            ],
            [
                'id' => '3',
                'name' => '氏名印',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '380',
                //'division' => '',
            ],
            [
                'id' => '4',
                'name' => 'おたよりｹｰｽ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '310',
                //'division' => '',
            ],
            [
                'id' => '5',
                'name' => '通園ﾘｭｯｸ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '3250',
                //'division' => '',
            ],
            [
                'id' => '6',
                'name' => '通園手さげﾊﾞｯｸ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '520',
                //'division' => '',
            ],
            [
                'id' => '7',
                'name' => '組帽子',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '820',
                //'division' => '',
            ],
            [
                'id' => '8',
                'name' => 'ﾍﾞｯﾄ用ｼｰﾂ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '2000',
                //'division' => '',
            ],
            [
                'id' => '9',
                'name' => '諸費袋',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '50',
                //'division' => '',
            ],
            [
                'id' => '10',
                'name' => 'ネームプレート（2枚組）',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '200',
                //'division' => '',
            ],
            [
                'id' => '11',
                'name' => '上靴',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '1550',
                //'division' => '',
            ],
            [
                'id' => '12',
                'name' => 'お誕生絵本（全園児）',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '370',
                //'division' => '',
            ],
            [
                'id' => '13',
                'name' => '連絡帳',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '150',
                //'division' => '',
            ],
            [
                'id' => '14',
                'name' => '自由画帳（A4）',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '200',
                //'division' => '',
            ],
            [
                'id' => '15',
                'name' => 'ｸﾚﾖﾝ12色',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '560',
                //'division' => '',
            ],
            [
                'id' => '16',
                'name' => 'ｽﾎﾟｰﾂｳｪｱ（半袖）',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '1500',
                //'division' => '',
            ],
            [
                'id' => 'ｽﾎﾟｰﾂｳｪｱ（長袖）',
                'name' => '17',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '1750',
                //'division' => '',
            ],
            [
                'id' => '18',
                'name' => '紺半ｽﾞﾎﾞﾝ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '1400',
                //'division' => '',
            ],
            [
                'id' => '19',
                'name' => 'セーラ制服',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '4000',
                //'division' => '',
            ],
            [
                'id' => '20',
                'name' => '制作ｽﾓｯｸ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '1400',
                //'division' => '',
            ],
            [
                'id' => '21',
                'name' => 'お道具箱',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '590',
                //'division' => '',
            ],
            [
                'id' => '22',
                'name' => 'はさみ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '500',
                //'division' => '',
            ],
            [
                'id' => '23',
                'name' => 'のり',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '210',
                //'division' => '',
            ],
            [
                'id' => '24',
                'name' => 'ｸﾚﾖﾝ16色',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '610',
                //'division' => '',
            ],
            [
                'id' => '25',
                'name' => '自由画帳（B3）',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '210',
                //'division' => '',
            ],
            [
                'id' => '26',
                'name' => '粘土',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '460',
                //'division' => '',
            ],
            [
                'id' => '27',
                'name' => '粘土板',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '550',
                //'division' => '',
            ],
            [
                'id' => '28',
                'name' => '粘土ｹｰｽ（ﾍﾗ付き）',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '590',
                //'division' => '',
            ],
            [
                'id' => '29',
                'name' => 'ﾁｪｯｸ半ｽﾞﾎﾞﾝ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '3500',
                //'division' => '',
            ],
            [
                'id' => '30',
                'name' => 'ﾏｰｶｰ10色',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '790',
                //'division' => '',
            ],
            [
                'id' => '31',
                'name' => 'お誕生ｱﾙﾊﾞﾑｶｰﾄﾞ',
                'img_path' => 'spplie_imgs/no_image.png',
                'supplier_id' => '',
                'price' => '300',
                //'division' => '',
            ]
        ]);
    }
}
